### ISSUE TITLE
Create Fire in the forest example.

### ISSUE THREAD

**Issue by agojunior** [pedro-andrade-inpe/calibration#102]
Create a fire in the forest example, that draws a chart using multiple Runs and SAMDE.

**Comment by agojunior** [comment]
My old fire in the forest model doesn't work anymore, so I'm studying how to recreate it using the new terrame functions.

**Comment by agojunior** [comment]
I remember that in the SAMDE example I have to test what ratio of forest:emptySpaces results in more tress surviving the fire.
But what I have to do using this example in multipleRuns?

**Comment by pedro-andrade-inpe** [comment]
Only execute a set of simulations with the same parameters and take the 
average deforestation in the end.

**Comment by agojunior** [comment]
import("ca")
import("calibration")

local map = Map
local chart = Chart
Map = function() end
Chart = Map
local fireForest = SAMDE{
	model = Fire,
	maxGen = 25,
	parameters = {empty = Choice{min = 0, max = 1}},
	maximize = true,
	fit = function(model)
		local trees = 0
		forEachCell(model.cs, function(cell)
			if cell.state == "forest" then
				trees = trees + 1
			end
		end)
		return trees
	end
}
Map = map
Chart = chart
print("end")
print(fireForest.fit)

The execution of the example never ends

**Comment by pedro-andrade-inpe** [comment]
Fire in the forest example cannot be used by SAMDE because it can produce different outputs for the same inputs. Because of that, it is not possible to compute a fitness for a single result of the model. It would be necessary to simulate several times and compute the average, what SAMDE does not do. I believe that SAMDE can only work with deterministic models. Check this in the SAMDE paper.

**Comment by agojunior** [comment]
At the end of the paper they mention: "In future work, [...] The authors also
intend to run tests in noisy functions to analyze SaMDE
behavior in this kind of problem"
So aparently SaMDE was not developed to work with this kind of models.

paper link: https://onedrive.live.com/redir?resid=50A40B914086BD50!4054&authkey=!ACNH3WpLEBuIOME&ithint=file%2cpdf)

**Comment by agojunior** [comment]
I can try to alter the fit function to execute the model more times with the same parameters and calculate the average result, but I don't now if it would work.
