### ISSUE TITLE
remove folderPath argument from MultipleRuns

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#105]
folderPath argument from MultipleRuns is unnecessary, as it is always possible to use .. to concatenate the path to the folder name in the argument folderName.

**Comment by agojunior** [comment]
Trying to use mkDir() to create a folder named "UtilsAlternativeTests" inside TerraME tmp folder results in error.
http://i.imgur.com/NfofhMi.png

**Comment by agojunior** [comment]
mkDir()
creates a folder corrrectly when the filePath is passed, but returns an error as if it did not worked.

**Comment by agojunior** [comment]
the error message was "file exists". Do mkDir() delete and ovewrite an existing file?
