### ISSUE TITLE
MultipleRuns with quantity

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#106]
MultipleRuns must have quantity as mandatory argument with strategies "repeated" and "sample". Verify this and implement alternative tests Use Utils:defaultTableValue and Utils:mandatoryArgument from TerraME to implement these verifications.

**Comment by agojunior** [comment]
this verification is currently made by the checkParameters function. So I will work on this issue together with #104
