### ISSUE TITLE
MultipleRuns:output()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#114]
It seems that MultipleRuns:output() function is never called. In fact, it should be called in the end of each simulation. Verify this and add a test.

**Comment by agojunior** [comment]
The function output is called at the end of every test with the others additional functions.

**Comment by agojunior** [comment]
The function output is called at the end of every test with the others additional functions by the testAddFunctions()
(Since Multiple Runs accepts additional user defined functions, I decided to treat the output function as any other user defined function)
