### ISSUE TITLE
example calibration using SAMDE

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#117]
Implement the model described in 

http://www.dpi.inpe.br/gilberto/cursos/cst-317-2014/exercise-epidemics.pdf

Exercise 4.4, calibrating the model firstly described in exercise  (parameters alpha and beta).

**Comment by agojunior** [comment]
infection.lua is working for now, may receive changes in the future.

**Comment by agojunior** [comment]
(as the total number of people in the simulation, is still not stable. It's varying slight by ~10 people.
