### ISSUE TITLE
Implement a way to hide Chart and Map automatically multipleRuns

### ISSUE THREAD

**Issue by agojunior** [pedro-andrade-inpe/calibration#126]
-- implement a way to hide this automatically as argument for MultipleRuns #ADDISSUE#
-- it should hide all observers, and then put them back...
mChart = Chart
Chart = function() end

 daisy-calibration example comments

**Comment by agojunior** [comment]
The main problem is that this don't work in the package tests

**Comment by pedro-andrade-inpe** [comment]
For now, you can just call clean() to remove them from the graphical interface. I will implement something better for the next TerraME version.

**Comment by pedro-andrade-inpe** [comment]
To solve this, use
https://github.com/TerraME/terrame/issues/903
to be released in TerraME 2.0.
