### ISSUE TITLE
implement type Calibration

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#13]
Implement type Calibration with parameters model, parameters, and fit, and function run().

**Comment by agojunior** [comment]
shouldn't we close this issue since we are not going to implement the type calibration any longer? Since it's been separated in SAMDE.lua and MultipleRuns.lua

**Comment by pedro-andrade-inpe** [comment]
Not yet. SAMDE issues are still being elaborated.

**Comment by agojunior** [comment]
Calibration type became SamdeType
