### ISSUE TITLE
remove strategy repeated from MultipleRuns?

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#133]
Think about removing the strategy repeated from MultipleRuns. It seems that all the other strategies should have the option to repeat the simulation if needed.

**Comment by pedro-andrade-inpe** [comment]
@agojunior I need you to answer this question.

**Comment by agojunior** [comment]
I only noticed your comment in this issue today. I think the repeated strategy can be removed but I don't know if it's necessary.
1. The same result can be acquired with a selected strategy using a table with single scenario. But the parameters will have to be passed inside a table of scenarios in order for it to work.
 2.The factorial strategy already has a repeaty function implemented, but the sample function does not.
3.  In case of the sample strategy, it would need 2 different quantity arguments, the first for the number of random samples, and a second for the number times those samples would be repeated. 
4. A new bollean argument "repeat" will be required by the MultipleRuns function, default would be false.
5.The sample strategy uses quantity to determine the number of random samples, and those random samples may already repeat.

**Comment by agojunior** [comment]
I do believe the repeated strategy should not be removed, can I close this issue? (all strategies have a "repeat results" implemented as in the last release 0.1.2)
