### ISSUE TITLE
Update to TerraME 2.0

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#137]
Update calibration to TerraME 2.0. It has some changes related to Model. See the documentation.

**Comment by agojunior** [comment]
Everything is done, except for the goodness-of-fit examples that use .map database, I'll try to find examples in the terrame base package that use .map databases and fix the problem, however if i'm not able to fix it, i'll change the examples to use .csv databases that are working correctly.
(I'm using the today version of terrame on this link: https://drive.google.com/folderview?id=0B68zAwnr4BGPfldsaWtLNmJFU1pDYjg4eHNNTkJ5VjI0blBpb2FtVmRKNjRZX2tnN0oydE0&usp=sharing#list
