### ISSUE TITLE
Replace MultipleRun:repeats by repeat

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#143]
Use singular instead. Update all tests and examples that use it.

**Comment by agojunior** [comment]
At first I tried using 'repeat', but then the world turned yellow in sublime, as if it was a function and I changed to 'repeats'.
I have tried changing it back to 'repeat' but it does not work as it is apparently a reserved world in lua: http://i.imgur.com/7EIn9MR.png
