### ISSUE TITLE
MultipleRuns is duplicating the number of elements of a parameter in its output

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#145]
See the example below:

```lua
import("sysdyn")
import("calibration")

mr = MultipleRuns{
    model = PredatorPrey,
    parameters = {preyGrowth = Choice{min=0.1, max=0.5, step = 0.1}, finalTime = 100},
    hideGraphs = true,
    output = {"maxRabbits", "preyGrowth"}
}

print(vardump(mr))

Chart{
    data = mr,
    select = "maxRabbits",
    xAxis = "preyGrowth"
}
```

TerraME cannot run this script because `Argument 'data.preyGrowth' should have 5 elements, got 10.`

**Comment by agojunior** [comment]
multipleRuns already saves all parameters entered on the parameters table, as Choice{}
when you use output = {preyGrowth} is as if you are asking him to save that same parameter again.
I'll change so output ={preyGrowth} generates an error.

**Comment by agojunior** [comment]
The maxRabbits parameter does not exist in the predatorPrey model (sysDyn)
I changed the parameter to "rabbits" and it worked

**Comment by agojunior** [comment]
This could works as intended:

import("sysdyn")
import("calibration")

mr = MultipleRuns{
    model = PredatorPrey,
    parameters = {preyGrowth = Choice{min=0.1, max=0.5, step = 0.1}, finalTime = 100},
    hideGraphs = true,
    output = {"maxRabbits"}
}

print(vardump(mr))

Chart{
    data = mr,
    select = "maxRabbits",
    xAxis = "preyGrowth"
}

**Comment by agojunior** [comment]
If you think it's more efficient, I can change multipleRuns so it does not save any parameter output unless it's in the output table
