### ISSUE TITLE
new type MultipleRuns

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#31]
Implement type MultipleRuns, that gets the following parameters:

- model: a Model (in the current version of TerraME, a function). Compulsory.
- strategy: one of "selected", "repeat", "factorial", "sample". Optional and can be inferred from the arguments below.
- finalTime: a number with the final time of the simulation. Optional.
- parameters: a table with the parameters to be used. Optional. If it is a table of tables then the strategy is "selected".
- quantity: the number of simulation runs. Optional. If using quantity and there is some choice in parameters, then the strategy is "sample". Otherwise (but still using quantity), the strategy is "repeat". Otherwise, the strategy is factorial. If using quantity and parameters is a table with table then it should stop with an error.
- output: a function executed at the end of the simulation of each Model. Optional.

The implementation of the strategies do not belong to this issue.

**Comment by pedro-andrade-inpe** [comment]
The newest version of terrame implements type(model) == "Model", not "function" anymore.

**Comment by pedro-andrade-inpe** [comment]
The argument finalTime can be removed from MultipleRuns, because this parameter can be used in the values of `parameters'.

**Comment by agojunior** [comment]
All MultipleRuns issues already have been closed, so can I close this?

**Comment by agojunior** [comment]
Note:I'm not considering "question" labelled issues, because they are not for the program first version
