### ISSUE TITLE
Verify if all Models can be instantiated for MultipleRuns

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#33]
Implement a function called "checkParameters". It should belong to a new file called Utils.lua and gets a Model and a description of parameters (used by MultipleRuns) and check if it is possible to instantiate all the combinations of the parameters. Match the types of the arguments, check if parameters have all the compulsory arguments (those that do not have a default value, see the documentation of Model), and if all the choice values are subsets of the choice values of the Model. It needs to be implemented as a function because the calibration methods will also use it.

**Comment by agojunior** [comment]
how do I check to see if a choice value is a subset of the model choice?
How can I get to the x parameters in the model to compare them with the x parameters in the mutlipleRuns type?

**Comment by pedro-andrade-inpe** [comment]
Q: how do I check to see if a choice value is a subset of the model choice?

A:
min(calibration) = min(model) + k * step(model), with k integer >= 0
max(calibration) = max(model) + k * step(model), with k integer <= 0
step(calibration) = step(model) * k, with k integer >= 0

On 4/1/15 23:03, Antonio Gomes de Oliveira Junior wrote:
> how do I check to see if a choice value is a subset of the model choice?
> How can I get to the x parameters in the model to compare them with the
> x parameters in the mutlipleRuns type?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pedro-andrade-inpe/calibration/issues/33#issuecomment-88693214>.
>

-- 
Pedro R. Andrade, Dr.
Earth System Science Center (CCST)
National Institute for Space Research (INPE)
Sao Jose dos Campos, Brazil

**Comment by pedro-andrade-inpe** [comment]
```lua
m = Model{
    a = 2,
    b = Choice{min = 5},
    init = function() end
}

forEachElement(m(), function(idx, _, mtype)
    print(idx, mtype)
end)
```
