### ISSUE TITLE
parameter 'output' for MultipleRuns

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#42]
MultipleRuns should get an additional optional argument 'output', a function that gets a model as argument saves some information about the result of the model. This function must be executed in the end of the simulation in the following order:

0 - save the location of the current directory. See FileSystem:currentDir
1 - create a folder with the name of the simulation  #41 See FileSystem:mkDir
2 - change the current dir to the created dir. See FileSystem:chDir
3 - execute output(model)
4 - change the current dir to the original dir.

**Comment by agojunior** [comment]
Can I use the http://keplerproject.github.io/luafilesystem/index.html library?
because I have installed it on my PC but I'm still not able to use it on my project.

**Comment by agojunior** [comment]
forget about the problem, I was reading the reference in the official site, however after reading terraME documentation I noticed the functions have slightly different names
