### ISSUE TITLE
additional functions as arguments to MultipleRuns

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#43]
MultipleRuns can take additional functions. The functions names cannot have the same name of the arguments used in "parameters". For each additional function, in the end of each simulation, the function should be called with the model instance and the returning value must be added to the returning table of MultipleRuns, in a vield with the same name of the function name. For example:

```lua
r = MultipleRuns{
    model = MyModel,
    parameters = {water = 10, rain = 20},
    total = function(model)
        ...
    end,
    quantity = 10,
    finalTime = 10
}
```

should return a table like:

```lua
r.simulations == {"1", "2", "...", "10"}
r.water = {10, 10, 10, ..., 10}
r.rain = {20, 20, 20, ... 20}
r.total = {200, 100, 50, ..., 100} -- values returned from total(model)
type(r) == "MultipleRuns"
```

**Comment by agojunior** [comment]
How can I get a function name and use it like a string?

**Comment by agojunior** [comment]
How can I get a function name and use it like a string? I'm trying to use debug.info for now...

**Comment by pedro-andrade-inpe** [comment]
Antonio, you do not get the function name. In fact, you get the function itself! So you only need to call the function. Example:

```lua
function execute(data)
    return data.operator(data.a, data.b)
end

function sum(a,b)
    return a + b
end

print(execute{a = 2, b = 5, operator = sum})
```

**Comment by agojunior** [comment]
I need the function name string to create a variable in the resultTable with the same name as the function, but I think i got an idea of how to do it.
