### ISSUE TITLE
MultipleRuns:csv(file, sep)

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#44]
Allow MultipleRuns to be saved in a csv file. Use Utils:CSVwrite  to save the file.

**Comment by agojunior** [comment]
Implemented function saveCSVResult forr Multiple Runs.
However, everytime I try to use CSVwrite this bug  happens:

"Wrong execution, got error: '...ocuments/TerraME/terrame/bin/packages/base/lua/Utils.lua:946: bad argument #1 to 'pairs' (table expected, got number)'."

when the argument #1 IS A  TABLE, so this error should not be happening.

Example of execution:

>>print(type(CSVTable[idx])
table
>>CSVwrite(CSVTable[idx], "x.csv", ";")
Wrong execution, got error: '...ocuments/TerraME/terrame/bin/packages/base/lua/Utils.lua:946: bad argument #1 to 'pairs' (table expected, got number)'.
