### ISSUE TITLE
Type SAMDE

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#50]
Implement type SAMDE. It returns the fittest individual (an instance of a Model), and the fit. It has a compulsory parameter fit() that returns a number according to the results of the simulation of an instance of a Model. It should verify the 'parameters' and 'model' in the same way of MultipleRus.

```lua
instance, fit = SaMDE{
    model = MyModel,
    parameters = {
        water = choice{min = 10, max = 20},
        rain = choice{min = 10, max = 20}
    },
    fit = function(model)
        return model.result
    end,
    ...
}

instance.obscs:save(“file.png”)
print(fit)
print(instance)
```

Verify the parameters of the algorithm to be added to "...".

**Comment by agojunior** [comment]
Edit: The Parameters used in SAMDE are 
varMatrix = {{10,20},{10,20}}
dim = 2,
model = MyModel,
paramList = {"water","rain"},
finalTime = 1,
fit = ( the fit function)

Obs: SaMDE does not accept Step in range of values.

**Comment by pedro-andrade-inpe** [comment]
See #65 for the returning value.

**Comment by agojunior** [comment]
This should have been closed a long time ago.
