### ISSUE TITLE
Adapt SaMDE to work with fit()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#61]
The current internal implementation of SaMDE uses the returning value of model described as a function as a value for fit(). Adapt the internal implementation of SaMDE to work with a function fit() that is called in the end of the simulation of each model in order to get its fitness. It guarantees that the model is separated from the fit, which means that one can have different fit functions for a given model, whithout having to change the source code of the model.

**Comment by agojunior** [comment]
SAMDE already uses fit().
