### ISSUE TITLE
returning value of SaMDE

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#65]
The returning value of SaMDE should be an object of type  "SaMDE". It should have three attributes:
1) instance: the fittest individual of the population
2) fit: the result of fit() for the fittest individual
3) generations: the number of generations simulated.

**Comment by agojunior** [comment]
(now SAMDE type executes automatically without the need to call typeInstance:execute().
when I closed this issue, the execute function was the one with this return value, but now the SAMDE type itself returns it)
