### ISSUE TITLE
MultiLevel

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#71]
Convert continuous and discreteCostanzaMultiLevel into one single function: MultiLevel, that takes named arguments:

```lua
result = PixelByPixel{
    cs1 = mycs,
    cs2 = mycs2, -- default is cs1
    attr1 = "myattr",
    attr2 = "myattr2", -- default is attr1, 
    -- but the user must set at least one of cs2 or attr2
    continuous = true -- default is false (discrete)
}
```

**Comment by agojunior** [comment]
should I use the discreteCostanzaMultiLevel or the newDiscreteCostanzaMultilevel?
The "old" version overlaps the square while going throught the map, and discards values when they don't fit the square, however it's result is closer to the one described in the /costanza Paper.

For now I will use the newDiscreteMultiLevel function.

**Comment by pedro-andrade-inpe** [comment]
What do you mean by "don't fit the square"?


On 3/10/15 09:44, Antonio Gomes de Oliveira Junior wrote:
> should I use the discreteCostanzaMultiLevel or the
> newDiscreteCostanzaMultilevel?
> The "old" version overlaps the square while going throught the map, and
> discards values when they don't fit the square, however it's result is
> closer to the one described in the /costanza Paper.
>
> For now I will use the newDiscreteMultiLevel function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pedro-andrade-inpe/calibration/issues/71#issuecomment-78045806>.
>

-- 
Pedro R. Andrade, Dr.
Earth System Science Center (CCST)
National Institute for Space Research (INPE)
Sao Jose dos Campos, Brazil

**Comment by agojunior** [comment]
The costanza paper descibres a square that's considered a single element.
 When going throught the map, if the map is odd and the square is even, then some values won't fit the square to be calculated as a single elemented, in the "old" discreteMultiLevel those values are simple ignored

**Comment by agojunior** [comment]
In newer updates, I decided to remove the "old" version since the "new" one is now closer to the original result. And is much more refined than the old version.
