### ISSUE TITLE
MultipleRuns example

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/calibration#96]
```lua

local c1 = MultipleRuns{
    model = yeast,
    parameters = {rate = Choice{min = 0, max = 2.5, step = 0.1}},
    fit = function(model)
        return math.sqrt (model.rms)
    end
}

-- some way to draw a Chart with the output of fit according to rate

```

**Comment by agojunior** [comment]
Which strategy? (Factorial, Repeated, Sample, Selected, one for each?)

**Comment by pedro-andrade-inpe** [comment]
As the objective is to draw a Chart, the strategy should be Factorial, ranging from `min` to `max`. Note that the Chart will be possible in this case because there is only one parameter to be used as x axis.

**Comment by agojunior** [comment]
sysDyn MultipleRuns example created.
